In [3]:
import pandas as pd

In [33]:
df=pd.DataFrame([[1,4,5],[4,5,6],[34,53,65]],columns=['q','w','e'],index=['a','b','c'])

In [58]:
df=pd.read_csv('/content/student-mat.csv')

In [44]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [36]:
display(df)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [37]:
df.sample(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
93,GP,F,16,U,GT3,T,4,2,teacher,services,...,5,3,3,1,1,1,0,11,10,10
184,GP,F,16,U,GT3,T,3,2,other,other,...,1,2,2,1,2,1,14,12,13,12
312,GP,M,19,U,GT3,T,1,2,other,services,...,4,5,2,2,2,4,3,13,11,11
234,GP,M,16,U,LE3,T,1,1,other,other,...,3,4,2,1,1,5,18,9,7,6
302,GP,F,17,U,GT3,T,4,2,other,other,...,4,3,3,1,1,3,0,15,12,14
142,GP,F,15,U,GT3,T,4,4,teacher,services,...,4,2,2,1,1,5,2,9,11,11
105,GP,F,15,U,GT3,A,3,3,other,health,...,4,3,3,1,1,4,10,10,11,11
351,MS,M,17,U,GT3,T,3,3,health,other,...,4,5,4,2,3,3,2,13,13,13
273,GP,M,17,R,GT3,T,1,2,at_home,at_home,...,3,5,2,2,2,1,2,15,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10

In [38]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [39]:
#loc(work with row and column) and iloc(works with index number)
df.loc[0:4,["school","age","address"]]

  school  age address
0     GP   18       U
1     GP   17       U
2     GP   15       U
3     GP   15       U
4     GP   16       U

In [41]:
#we can replace numeric index with any column

df.index=df.Fjob

In [42]:
df.loc["at_home","school"]

Fjob
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    GP
at_home    MS
at_home    MS
at_home    MS
at_home    MS
Name: school, dtype: object

In [45]:
 #we can modify value at specific place
 df.loc[2,'age']=17

In [46]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,17,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [57]:
#sorting with the help of column
df.sort_values("school",ascending=False, inplace=True)
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
394     MS   M   19       U     LE3       T     1     1     other   at_home
391     MS   M   17       U     LE3       T     3     1  services  services
373     MS   F   17       R     GT3       T     1     2     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
392     MS   M   21       R     GT3       T     1     1     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
312     GP   M   19       U     GT3       T     1     2     other  services
314     GP   F   19       U     GT3       T     1     1   at_home    health
334     GP   F   18       R     GT3       T     2     2   at_home     other
335     GP   F   17       U     GT3       T     3     4  services     other
197     GP   M   16       R     LE3       T     3     3   teacher     other

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
394  ...      3        2      3     3     3      5        5   8   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
373  ...      3        5      5     1     3      1       14   6   5   5
393  ...      4        4      1     3     4      5        0  11  12  10
392  ...      5        5      3     3     3      3        3  10   8   7
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
312  ...      4        5      2     2     2      4        3  13  11  11
314  ...      4        1      2     1     1      3       14  15  13  13
334  ...      4        4      4     1     1      4        0  10   9   0
335  ...      4        4      5     1     3      5       16  16  15  15
197  ...      3        3      4     3     5      3        8   9   9  10

[395 rows x 33 columns]

In [59]:
#Filtering Data
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [60]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [81]:
df.loc[df["age"]>15,["school","sex","age"]]  #getting students with age GT 15
#or
df[df["age"]>15]
#OR
df[(df["age"]>15) & (df["health"]>3)] #multiconditions

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [85]:
#can use str method for applying conditions
df[df['Mjob'].str.contains("at_home")]
df[df['Mjob'].str.contains("at_home|health")]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10

In [93]:
#3Getting confortable with QUERY function

df.query('age > 15')

df.query('famrel==4')

df.query('health>2' and 'Mjob=="at_home"')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
39,GP,F,15,R,GT3,T,2,2,at_home,other,...,4,3,1,1,1,2,8,14,13,13
79,GP,F,16,U,GT3,T,3,4,at_home,other,...,2,4,3,1,2,3,12,5,5,5
86,GP,F,16,U,LE3,T,2,2,at_home,other,...,4,3,4,1,2,2,4,8,7,6
95,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,2,7,10,10
112,GP,F,16,U,GT3,T,2,2,at_home,other,...,3,1,2,1,1,5,6,10,13,13
120,GP,F,15,U,GT3,T,1,2,at_home,services,...,3,2,3,1,2,1,2,16,15,15
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,3,4,2,1,1,5,2,7,8,9
131,GP,F,15,U,GT3,T,1,1,at_home,other,...,4,3,3,1,2,4,0,8,0,0
134,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,5,3,3,1,1,5,0,9,0,0
136,GP,M,17,R,GT3,T,3,4,at_home,other,...,5,4,5,2,4,5,0,10,0,0
143,GP,F,16,U,LE3,T,1,1,at_home,at_home,...,3,4,4,3,3,1,2,14,14,13
147,GP,F,15,U,GT3,T,1,2,at_home,other,...,4,3,2,1,1,5,2,10,11,11
151,GP,M,16,U,LE3,T,2,1,at_home,other,...,4,4,4,3,5,5,6,12,13,14
155,GP,M,15,R,GT3,T,2,3,at_home,services,...,4,4,4,1,1,1,2,11,8,8
157,GP,F,18,R,GT3,T,1,1,at_home,other,...,5,2,5,1,5,4,6,9,8,10
158,GP,M,16,R,GT3,T,2,2,at_home,other,...,4,2,2,1,2,3,2,17,15,15
160,GP,M,17,R,LE3,T,2,1,at_home,other,...,3,3,2,2,2,5,0,7,6,0
163,GP,M,17,U,GT3,T,1,3,at_home,services,...,5,3,3,1,4,2,2,10,10,10
173,GP,F,16,U,GT3,T,1,3,at_home,services,...,4,3,5,1,1,3,0,8,7,0
189,GP,M,17,R,GT3,T,1,2,at_home,other,...,3,1,3,1,5,3,4,8,9,10
191,GP,F,17,U,GT3,T,1,1,at_home,services,...,5,3,3,1,1,3,0,8,8,9
192,GP,M,17,U,GT3,T,1,2,at_home,services,...,4,4,4,4,5,5,12,7,8,8
205,GP,F,17,U,GT3,T,3,4,at_home,services,...,4,4,3,3,4,5,28,10,9,9
208,GP,F,16,U,GT3,T,1,1,at_home,other,...,4,3,2,1,4,5,6,9,9,10
218,GP,F,17,U,GT3,T,2,3,at_home,other,...,3,3,3,1,4,3,3,7,7,8
219,GP,F,17,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,1,4,4,9,10,10
220,GP,F,17,R,GT3,T,2,1,at_home,services,...,4,2,5,1,2,5,2,6,6,6
221,GP,F,17,U,GT3,T,1,1,at_home,other,...,4,3,4,1,1,5,0,6,5,0
228,GP,M,18,U,LE3,T,2,1,at_home,other,...,4,3,2,4,5,3,14,10,8,9
235,GP,M,16,U,GT3,T,3,2,at_home,other,...,5,3,3,1,3,2,10,11,9,10
238,GP,F,17,R,GT3,T,2,1,at_home,services,...,2,1,1,1,1,3,2,13,11,11
251,GP,M,16,U,GT3,T,3,3,at_home,other,...,5,3,3,1,3,2,6,7,10,10
264,GP,F,18,U,GT3,T,2,2,at_home,services,...,4,3,3,1,1,3,0,9,10,0
273,GP,M,17,R,GT3,T,1,2,at_home,at_home,...,3,5,2,2,2,1,2,15,14,14
274,GP,F,17,U,GT3,T,2,4,at_home,health,...,4,3,3,1,1,1,2,10,10,10
282,GP,F,18,R,LE3,T,1,1,at_home,other,...,5,2,2,1,1,3,1,12,12,12
286,GP,F,18,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,2,2,5,18,18,19
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,4,4,3,1,3,3,18,12,10,10
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,3,4,1,1,1,2,20,14,12,13
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,4,1,2,1,1,3,14,15,13,13
318,GP,F,17,R,GT3,T,3,4,at_home,services,...,4,3,4,2,5,5,0,11,11,10
324,GP,F,17,U,LE3,T,0,2,at_home,at_home,...,3,3,3,2,3,2,0,16,15,15
331,GP,F,17,R,GT3,T,2,4,at_home,other,...,4,4,3,1,1,5,7,12,14,14
334,GP,F,18,R,GT3,T,2,2,at_home,other,...,4,4,4,1,1,4,0,10,9,0
343,GP,F,17,U,GT3,A,2,2,at_home,at_home,...,3,3,1,1,2,4,0,9,8,0
344,GP,F,18,U,GT3,T,2,3,at_home,other,...,4,3,3,1,2,3,4,11,10,10
352,MS,M,18,U,LE3,T,1,3,at_home,services,...,4,3,3,2,3,3,7,8,7,8
359,MS,F,18,U,LE3,T,1,1,at_home,services,...,5,3,2,1,1,4,0,18,16,16
360,MS,F,18,R,LE3,A,1,4,at_home,other,...,4,3,4,1,4,5,0,13,13,13
361,MS,M,18,R,LE3,T,1,1,at_home,other,...,4,4,3,2,3,5,2,13,12,12
363,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,0,16,15,15
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10

add and remove columns

In [98]:
#add specific value
df.loc[1,'age']=32
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,32,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [115]:
#adding new column

df['new_col']=5

In [110]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,new_col
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,321
1,GP,F,32,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,321
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,321
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,321
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,321
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,321
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,321
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,321
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,321

In [111]:
import numpy as np
df['new_col']=np.where(df['health']==3,400,231)

In [112]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,new_col
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,400
1,GP,F,32,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,400
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,400
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,231
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,4,4,5,4,11,9,9,9,231
391,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,3,14,16,16,231
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,3,3,3,3,3,10,8,7,400
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,0,11,12,10,231
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,2,3,3,3,5,5,8,9,9,231

In [113]:
df.sample()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,new_col
224,GP,F,16,U,GT3,T,4,4,teacher,services,...,3,2,1,1,5,0,13,13,14,231

In [114]:
df=df.drop('new_col',axis=1)

In [116]:
#adding new column by multipying
df['multiply']=df['health']*df['new_col']

In [121]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,new_col,multiply
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,5,15
1,GP,F,32,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,5,15
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,5,15
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,5,25
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,5,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,5,20
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,5,10
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,5,15
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,5,25
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,5,25

In [122]:
#can rename the columns

df.rename(columns={'multiply':'Rough_val'})

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,new_col,Rough_val
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,5,15
1,GP,F,32,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,5,15
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,5,15
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,5,25
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,5,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,5,20
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,5,10
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,5,15
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,5,25
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,5,25

In [123]:
new_df=pd.read_csv('/content/base_etablissement_par_tranche_effectif.csv')

In [124]:
new_df

,CODGEO,LIBGEO,REG,DEP,E14TST,E14TS0ND,E14TS1,E14TS6,E14TS10,E14TS20,E14TS50,E14TS100,E14TS200,E14TS500
0,01001,L'Abergement-Clémenciat,82,01,25,22,1,2,0,0,0,0,0,0
1,01002,L'Abergement-de-Varey,82,01,10,9,1,0,0,0,0,0,0,0
2,01004,Ambérieu-en-Bugey,82,01,996,577,272,63,46,24,9,3,2,0
3,01005,Ambérieux-en-Dombes,82,01,99,73,20,3,1,2,0,0,0,0
4,01006,Ambléon,82,01,4,4,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36676,97613,M'Tsangamouji,6,976,169,169,0,0,0,0,0,0,0,0
36677,97614,Ouangani,6,976,230,230,0,0,0,0,0,0,0,0
36678,97615,Pamandzi,6,976,569,569,0,0,0,0,0,0,0,0
36679,97616,Sada,6,976,345,345,0,0,0,0,0,0,0,0
36680,97617,Tsingoni,6,976,348,348,0,0,0,0,0,0,0,0